name: flowtask

services:
  app:
    image: node:18
    build: .
    command: \
              "npm", "init", "-y"
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data: