version: '3'
services:
  flask:
    build: ./backend
    environment:
      FLASK_ENV: production
    expose:
      - 5000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/letsencrypt
      - ./backend:/var/www/html
    depends_on:
      - flask