name: flowtask-tg.ru

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install depencies
        run: |
          npm install
          npm install pm2

      - name: deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/flowtask-tg.ru
            git pull origin main
            npm install --production
            pm2 restart all
